import { getShuffledIndexes } from "../../utils";

const listSoalNounBahasaInggris = [
  { noun: "aberration", arti: "penyimpangan" },
  { noun: "abstinence", arti: "pantangan" },
  { noun: "accolade", arti: "penghargaan" },
  { noun: "acumen", arti: "ketajaman" },
  { noun: "adversity", arti: "kesulitan" },
  { noun: "advocate", arti: "pendukung" },
  { noun: "aesthetic", arti: "estetika" },
  { noun: "affinity", arti: "kesamaan" },
  { noun: "agenda", arti: "agenda" },
  { noun: "allegiance", arti: "kesetiaan" },
  { noun: "altruism", arti: "altruisme" },
  { noun: "ambivalence", arti: "perasaan campur aduk" },
  { noun: "anecdote", arti: "anekdot" },
  { noun: "anomaly", arti: "anomali" },
  { noun: "antagonism", arti: "permusuhan" },
  { noun: "apathy", arti: "ketidakpedulian" },
  { noun: "appeasement", arti: "penenangan" },
  { noun: "apprehension", arti: "kekhawatiran" },
  { noun: "aptitude", arti: "bakat" },
  { noun: "ardor", arti: "semangat" },
  { noun: "artifact", arti: "artefak" },
  { noun: "aspiration", arti: "aspirasi" },
  { noun: "assertion", arti: "pernyataan" },
  { noun: "assimilation", arti: "asimilasi" },
  { noun: "atrocity", arti: "kekejaman" },
  { noun: "attainment", arti: "pencapaian" },
  { noun: "audacity", arti: "keberanian" },
  { noun: "austerity", arti: "kesederhanaan" },
  { noun: "authenticity", arti: "keaslian" },
  { noun: "autonomy", arti: "otonomi" },
  { noun: "aversion", arti: "keengganan" },
  { noun: "bane", arti: "kutukan" },
  { noun: "bequest", arti: "warisan" },
  { noun: "bias", arti: "bias" },
  { noun: "brevity", arti: "singkatnya" },
  { noun: "brunt", arti: "beban utama" },
  { noun: "cacophony", arti: "kekacauan suara" },
  { noun: "candor", arti: "kejujuran" },
  { noun: "caprice", arti: "keanehan" },
  { noun: "catalyst", arti: "katalisator" },
  { noun: "catharsis", arti: "katarsis" },
  { noun: "causality", arti: "kausalitas" },
  { noun: "celerity", arti: "kecepatan" },
  { noun: "censure", arti: "kecaman" },
  { noun: "chasm", arti: "jurang" },
  { noun: "chronicle", arti: "kronik" },
  { noun: "clout", arti: "pengaruh" },
  { noun: "coercion", arti: "pemaksaan" },
  { noun: "cognition", arti: "kognisi" },
  { noun: "colleague", arti: "rekan kerja" },
  { noun: "commencement", arti: "permulaan" },
  { noun: "compendium", arti: "ringkasan" },
  { noun: "complacency", arti: "kepuasan diri" },
  { noun: "composure", arti: "ketenangan" },
  { noun: "concession", arti: "konsesi" },
  { noun: "concurrence", arti: "kesepakatan" },
  { noun: "condolence", arti: "belasungkawa" },
  { noun: "conflagration", arti: "kebakaran besar" },
  { noun: "connotation", arti: "konotasi" },
  { noun: "consensus", arti: "kesepakatan umum" },
  { noun: "consternation", arti: "kebingungan" },
  { noun: "contention", arti: "perselisihan" },
  { noun: "contingency", arti: "kemungkinan" },
  { noun: "contradiction", arti: "kontradiksi" },
  { noun: "conundrum", arti: "teka-teki" },
  { noun: "convergence", arti: "konvergensi" },
  { noun: "conviction", arti: "keyakinan" },
  { noun: "corollary", arti: "kesimpulan" },
  { noun: "corroboration", arti: "penguatan bukti" },
  { noun: "credibility", arti: "kredibilitas" },
  { noun: "culmination", arti: "puncak" },
  { noun: "cynicism", arti: "sinisme" },
  { noun: "dearth", arti: "kelangkaan" },
  { noun: "debacle", arti: "kehancuran" },
  { noun: "decadence", arti: "kemerosotan moral" },
  { noun: "decorum", arti: "kesopanan" },
  { noun: "deficiency", arti: "kekurangan" },
  { noun: "defiance", arti: "perlawanan" },
  { noun: "deference", arti: "penghormatan" },
  { noun: "degradation", arti: "degradasi" },
  { noun: "deliberation", arti: "pertimbangan" },
  { noun: "demeanor", arti: "sikap" },
  { noun: "demise", arti: "kematian" },
  { noun: "denunciation", arti: "kecaman" },
  { noun: "dereliction", arti: "pengabaian" },
  { noun: "deterrent", arti: "pencegah" },
  { noun: "detriment", arti: "kerugian" },
  { noun: "dexterity", arti: "ketangkasan" },
  { noun: "dichotomy", arti: "dikotomi" },
  { noun: "diligence", arti: "ketekunan" },
  { noun: "discrepancy", arti: "ketidaksesuaian" },
  { noun: "disdain", arti: "penghinaan" },
  { noun: "disparity", arti: "kesenjangan" },
  { noun: "disposition", arti: "kecenderungan" },
  { noun: "disrepute", arti: "kehinaan" },
  { noun: "dissension", arti: "perpecahan" },
  { noun: "dissonance", arti: "ketidakharmonisan" },
  { noun: "divergence", arti: "perbedaan" },
  { noun: "divinity", arti: "keilahian" },
  { noun: "dogma", arti: "dogma" },
  { noun: "dormancy", arti: "keadaan tidur" },
  { noun: "drudgery", arti: "pekerjaan membosankan" },
  { noun: "duplicity", arti: "kemunafikan" },
  { noun: "eccentricity", arti: "keunikan" },
  { noun: "efficacy", arti: "efikasi" },
  { noun: "eloquence", arti: "kelancaran berbicara" },
  { noun: "empathy", arti: "empati" },
  { noun: "enigma", arti: "misteri" },
  { noun: "enmity", arti: "permusuhan" },
  { noun: "entreaty", arti: "permohonan" },
  { noun: "epiphany", arti: "pencerahan" },
  { noun: "equanimity", arti: "keseimbangan emosi" },
  { noun: "equity", arti: "keadilan" },
  { noun: "espionage", arti: "spionase" },
  { noun: "esteem", arti: "penghargaan" },
  { noun: "ethos", arti: "etika" },
  { noun: "euphoria", arti: "kegembiraan" },
  { noun: "exacerbation", arti: "perburukan" },
  { noun: "exaltation", arti: "pengangkatan" },
  { noun: "exasperation", arti: "kemarahan" },
  { noun: "exclusion", arti: "pengecualian" },
  { noun: "exegesis", arti: "penafsiran" },
  { noun: "exhilaration", arti: "kegembiraan" },
  { noun: "expenditure", arti: "pengeluaran" },
  { noun: "explication", arti: "penjelasan" },
  { noun: "exuberance", arti: "keceriaan" },
  { noun: "facilitation", arti: "fasilitasi" },
  { noun: "feasibility", arti: "kelayakan" },
  { noun: "fidelity", arti: "kesetiaan" },
  { noun: "framework", arti: "kerangka kerja" },
  { noun: "friction", arti: "gesekan" },
  { noun: "fulfillment", arti: "pemenuhan" },
  { noun: "functionality", arti: "fungsi" },
  { noun: "funding", arti: "pendanaan" },
  { noun: "fusion", arti: "penggabungan" },
  { noun: "generation", arti: "generasi" },
  { noun: "gratification", arti: "kepuasan" },
  { noun: "groundwork", arti: "persiapan awal" },
  { noun: "growth", arti: "pertumbuhan" },
  { noun: "guideline", arti: "pedoman" },
  { noun: "hierarchy", arti: "hierarki" },
  { noun: "hindrance", arti: "hambatan" },
  { noun: "hospitality", arti: "keramahtamahan" },
  { noun: "hypothesis", arti: "hipotesis" },
  { noun: "implementation", arti: "implementasi" },
  { noun: "improvisation", arti: "improvisasi" },
  { noun: "incentive", arti: "insentif" },
  { noun: "incidence", arti: "kejadian" },
  { noun: "inclination", arti: "kecenderungan" },
  { noun: "inclusion", arti: "penyertaan" },
  { noun: "inconsistency", arti: "ketidak-konsistenan" },
  { noun: "increment", arti: "kenaikan" },
  { noun: "indemnity", arti: "ganti rugi" },
  { noun: "inefficiency", arti: "ketidakefisienan" },
  { noun: "inevitability", arti: "keniscayaan" },
  { noun: "infusion", arti: "injeksi dana" },
  { noun: "initiative", arti: "inisiatif" },
  { noun: "innovation", arti: "inovasi" },
  { noun: "insight", arti: "wawasan" },
  { noun: "inspection", arti: "pemeriksaan" },
  { noun: "inspiration", arti: "inspirasi" },
  { noun: "integration", arti: "integrasi" },
  { noun: "integrity", arti: "integritas" },
  { noun: "intention", arti: "niat" },
  { noun: "interaction", arti: "interaksi" },
  { noun: "interference", arti: "campur tangan" },
  { noun: "interpretation", arti: "penafsiran" },
  { noun: "intervention", arti: "intervensi" },
  { noun: "inventory", arti: "inventaris" },
  { noun: "investment", arti: "investasi" },
  { noun: "involvement", arti: "keterlibatan" },
  { noun: "justification", arti: "pembenaran" },
  { noun: "leadership", arti: "kepemimpinan" },
  { noun: "legitimacy", arti: "keabsahan" },
  { noun: "liability", arti: "kewajiban" },
  { noun: "litigation", arti: "proses hukum" },
  { noun: "logistics", arti: "logistik" },
  { noun: "longevity", arti: "usia panjang" },
  { noun: "maintenance", arti: "pemeliharaan" },
  { noun: "mandate", arti: "mandat" },
  { noun: "mediation", arti: "mediasi" },
  { noun: "merger", arti: "penggabungan" },
  { noun: "milestone", arti: "tonggak pencapaian" },
  { noun: "mitigation", arti: "pengurangan dampak" },
  { noun: "mobilization", arti: "mobilisasi" },
  { noun: "modification", arti: "modifikasi" },
  { noun: "momentum", arti: "momentum" },
  { noun: "monitoring", arti: "pemantauan" },
  { noun: "negotiation", arti: "negosiasi" },
  { noun: "niche", arti: "ceruk pasar" },
  { noun: "obligation", arti: "kewajiban" },
  { noun: "objective", arti: "tujuan" },
  { noun: "obstacle", arti: "halangan" },
  { noun: "optimization", arti: "optimisasi" },
  { noun: "orientation", arti: "orientasi" },
  { noun: "output", arti: "hasil keluaran" },
  { noun: "oversight", arti: "pengawasan" },
  { noun: "paradigm", arti: "paradigma" },
  { noun: "parameter", arti: "parameter" },
  { noun: "partnership", arti: "kemitraan" },
  { noun: "patent", arti: "paten" },
  { noun: "perception", arti: "persepsi" },
  { noun: "performance", arti: "kinerja" },
  { noun: "persistence", arti: "ketekunan" },
  { noun: "pertinence", arti: "keterkaitan" },
  { noun: "phenomenon", arti: "fenomena" },
  { noun: "planning", arti: "perencanaan" },
  { noun: "plausibility", arti: "kemungkinan kebenaran" },
  { noun: "policy", arti: "kebijakan" },
  { noun: "portfolio", arti: "portofolio" },
  { noun: "precedent", arti: "preseden" },
  { noun: "precision", arti: "ketepatan" },
  { noun: "predecessor", arti: "pendahulu" },
  { noun: "prediction", arti: "prediksi" },
  { noun: "preference", arti: "preferensi" },
  { noun: "premise", arti: "premis" },
  { noun: "prevalence", arti: "prevalensi" },
  { noun: "priority", arti: "prioritas" },
  { noun: "probability", arti: "kemungkinan" },
  { noun: "procedure", arti: "prosedur" },
  { noun: "process", arti: "proses" },
  { noun: "procurement", arti: "pengadaan" },
  { noun: "productivity", arti: "produktivitas" },
  { noun: "projection", arti: "proyeksi" },
  { noun: "proliferation", arti: "penyebaran cepat" },
  { noun: "promotion", arti: "promosi" },
  { noun: "proponent", arti: "pendukung" },
  { noun: "prospect", arti: "prospek" },
  { noun: "protocol", arti: "protokol" },
  { noun: "provision", arti: "penyediaan" },
  { noun: "publicity", arti: "publisitas" },
  { noun: "qualification", arti: "kualifikasi" },
  { noun: "rapport", arti: "hubungan baik" },
  { noun: "rebuttal", arti: "sanggahan" },
  { noun: "reconciliation", arti: "rekonsiliasi" },
  { noun: "recruitment", arti: "rekrutmen" },
  { noun: "redundancy", arti: "pengulangan berlebih" },
  { noun: "refinement", arti: "penyempurnaan" },
  { noun: "regulation", arti: "regulasi" },
  { noun: "reinforcement", arti: "penguatan" },
  { noun: "reimbursement", arti: "penggantian biaya" },
  { noun: "reliability", arti: "keandalan" },
  { noun: "relevance", arti: "keterkaitan" },
  { noun: "remuneration", arti: "imbalan" },
  { noun: "repository", arti: "penyimpanan" },
  { noun: "resilience", arti: "ketangguhan" },
  { noun: "resourcefulness", arti: "kepandaian mengatasi masalah" },
  { noun: "restructuring", arti: "restrukturisasi" },
  { noun: "retention", arti: "retensi" },
  { noun: "revenue", arti: "pendapatan" },
  { noun: "revision", arti: "revisi" },
  { noun: "rhetoric", arti: "retorika" },
  { noun: "risk", arti: "risiko" },
];

export const SoalNounBahasaInggris = (jumlahSoal) => {
  if (jumlahSoal > listSoalNounBahasaInggris.length) {
    throw new Error("Jumlah soal melebihi jumlah data yang tersedia.");
  }
  if (jumlahSoal <= 0) {
    throw new Error("Jumlah soal harus lebih dari 0.");
  }

  let selectedIndexes = getShuffledIndexes(listSoalNounBahasaInggris.length)
    .slice(0, jumlahSoal)
    .sort((a, b) => a - b); // Mengurutkan indeks yang terpilih
  let indexSelectedIndexes = 0;

  let ListSoalFinal = listSoalNounBahasaInggris.map((item, index) => {
    if (selectedIndexes[indexSelectedIndexes] != index) return null; // Hanya ambil soal yang terpilih
    let arrayShuffleOpptions = getShuffledIndexes(
      listSoalNounBahasaInggris.length
    )
      .slice(0, 3)
      .map((i) => {
        if (i === index || i >= listSoalNounBahasaInggris.length) return null; // Hindari soal yang sama
        if (listSoalNounBahasaInggris[i].arti) {
          const sinonim = listSoalNounBahasaInggris[i].arti.split(", ")[0];
          if (sinonim === item.arti.split(", ")[0]) return null; // Hindari sinonim yang sama
          return sinonim;
        }
        return listSoalNounBahasaInggris[i].arti;
      });

    arrayShuffleOpptions.push(item.arti.split(", ")[0]); // Tambahkan sinonim yang benar
    arrayShuffleOpptions = arrayShuffleOpptions.filter(Boolean); // Hapus nilai null
    arrayShuffleOpptions = arrayShuffleOpptions.sort(() => Math.random() - 0.5); // Acak urutan pilihan jawaban
    arrayShuffleOpptions = [...new Set(arrayShuffleOpptions)]; // Hapus duplikat
    arrayShuffleOpptions = arrayShuffleOpptions.slice(0, 4); // Ambil 4 pilihan jawaban
    if (arrayShuffleOpptions.length < 4) {
      const additionalOptions = listSoalNounBahasaInggris
        .filter(
          (_, i) =>
            i !== index &&
            !arrayShuffleOpptions.includes(
              listSoalNounBahasaInggris[i].arti.split(", ")[0]
            )
        )
        .map((item) => item.arti.split(", ")[0])
        .slice(0, 4 - arrayShuffleOpptions.length);
      arrayShuffleOpptions = [...arrayShuffleOpptions, ...additionalOptions];
    }

    indexSelectedIndexes++; // Increment indexSelectedIndexes for the next iteration

    return {
      id: index + 1,
      question: `Apa arti dari kata "${item.noun}"?`,
      options: arrayShuffleOpptions,
      correctAnswer: item.arti.split(", ")[0],
    };
  });

  ListSoalFinal = ListSoalFinal.filter(Boolean).sort(() => Math.random() - 0.5);

  return ListSoalFinal.filter(Boolean); // Hapus nilai null dari soal yang tidak terpilih
};
